# 官方文档
# https://github.com/bestK/tv
# https://hub.docker.com/r/bestzwei/libretv
# 演示站
# https://libretv.is-an.org

---
version: "3"
# 最后编辑时间：2025-04-16
services:
  libretv:
    image: bestzwei/libretv:latest
    # 镜像地址
    container_name: libretv
    # 容器名字
    hostname: libretv
    # 主机名
    network_mode: bridge
    # 80端口有别的服务占用了，所以使用bridge
    ports:
      - 8999:80
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:80]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/libretv.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
