# 官网
# https://github.com/Danborad/spacemap
# https://hub.docker.com/r/zhong12138/spacemap

# 如果你懂docker容器路径映射的话，可以将全部需要的路径映射套在同一层容器路径之下(比如：/data)
# 然后变量中设置自动识别的扫描路径就直接写一个/data即可，而不需要每次新增路径映射后，变量中也要补上
# 但同时这种做法，会增加更长的文件扫描时间

version: '3'
# 最后编辑时间：2026-01-19
services:
  spacemap:
    image: zhong12138/spacemap:latest
    # 镜像名字
    container_name: spacemap
    # 容器名字
    hostname: spacemap
    # 主机名
    # user: root
    # 赋予root最高管理员权限，一般用不上，先写着注释掉
    volumes:
      - /vol1/1000/docker/spacemap:/app/data
      # 配置文件目录

      - /vol1/1000:/飞牛存储池1:ro
      # 映射宿主机目录到容器内，并设置为 ro(只读)

      # 书写示例，假设需要映射飞牛的存储池2总目录：- /vol2/1000:/飞牛存储池2:/飞牛存储池2:ro
      # 【这里替换为你想要扫描NAS的目录】:/【这里替换为任意名字】:ro

    environment:
      - PORT=7080
      # 自定义容器 WebUI 端口，默认为7080

      - TRIM_DATA_SHARE_PATHS=/飞牛存储池1
      # 设置预设的自动识别的扫描路径，多个路径用冒号 : 分隔
      # 这里的路径必须与 volumes(路径映射) 的容器内路径一致

      # 书写示例，假设路径映射中容器路径有/飞牛存储池1和/飞牛存储池2：- TRIM_DATA_SHARE_PATHS=/飞牛存储池1:/飞牛存储池2

    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 7080:7080
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
