# 官方文档
# https://lobehub.com
# https://lobehub.com/zh/blog/5-lobe-chat-web-ui-recommendation
# http://hub.docker.com/lobehub/lobe-chat

# 免费API，需要自己有github账号并用账号登录才可以获取到免费API
# 1、打开链接：https://github.com/chatanywhere/GPT_API_free
# 2、注册登录github账号
# 3、点击“ 申请内测免费Key”，下一步下一步即可

# 来自 有云转晴 的教程 (2024-06-12)
# https://www.bilibili.com/video/BV1M32KYXEDN
# https://www.ywsj365.com/archives/docker-da-jian-yi-ge-mian-fei-shi-yong-chatgpt-de-lobe-chat-ying-yong

# 免费版支持gpt-3.5-turbo, embedding, gpt-4。其中gpt-4由于价格过高，每天限制3次调用（0点刷新）。需要更稳定快速的gpt-4请使用付费版
# 免费版gpt-4由gpt-4o提供服务，支持识图等付费版API全部功能
# 转发Host1: https://api.chatanywhere.tech (国内中转，延时更低，host1和host2二选一)
# 转发Host2: https://api.chatanywhere.com.cn (国内中转，延时更低，host1和host2二选一)
# 转发Host3: https://api.chatanywhere.cn (国外使用,国内需要全局代理)
# 免费API Key限制100请求/天/IP&Key调用频率（gpt和embedding分开计算，各100次）

---
version: '3.9'
# 最后编辑时间：2024-11-22
# 该模板使用的为不具备数据库的版本
services:
  lobe-chat:
    image: lobehub/lobe-chat:latest
    # 镜像地址
    container_name: lobe-chat
    # 容器名字
    hostname: lobe-chat
    # 主机名
    environment:
      - ACCESS_CODE=123456
      # 访问密码
      - OPENAI_PROXY_URL=https://api.chatanywhere.tech
      # 代理地址，见上说明，也可以写上自己的代理地址
      - OPENAI_API_KEY=【这里替换为申请的api密钥】
      # api密钥，见上说明，切勿泄露
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 3210:3210
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/lobe-chat_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:3210]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/lobe-chat.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
