# 官方文档
# http://hub.docker.com/_/adminer
# https://www.adminer.org

---
version: "3"
# 最后编辑时间：2024-10-27
services:
  adminer:
    image: adminer:latest
    # 镜像地址
    container_name: adminer
    # 容器名字
    hostname: adminer
    # 主机名
    # environment:
      # - ADMINER_DESIGN=flat
      # WebUI主题风格，在官网中选择，填入此处，默认不写也可以
      # - ADMINER_PLUGINS=
      # 插件，如需使用，见下
      # https://www.adminer.org/en/plugins
    network_mode: bridge
    # network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    ports:
      - 8383:8080
      # WebUI 端口，威联通的WebUI为8080，所以要bridge改成别的端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:8080]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/adminer.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
