# 官方文档
# https://hub.docker.com/r/frooodle/s-pdf
# https://github.com/Stirling-Tools/Stirling-PDF

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  s-pdf:
    image: frooodle/s-pdf:latest
    # 镜像地址
    container_name: s-pdf
    # 容器名字
    hostname: s-pdf
    # 主机名
    volumes:
      - /Volume1/docker/s-pdf/configs:/configs
      # 配置文件目录
      - /Volume1/docker/s-pdf/logs:/logs
      # 日志文件目录
      - /Volume1/docker:/usr/share/tessdata
      # 图片上传目录
    network_mode: bridge
    # 推荐使用bridge模式，8000有别的docker镜像要用
    ports:
      - 8660:8000
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3