# 官方文档
# https://hub.docker.com/r/louislam/dockge
# https://dockge.kuma.pet

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  dockge:
    image: louislam/dockge:latest
    # 镜像地址
    container_name: dockge
    # 容器名字
    hostname: dockge
    # 主机名
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # docker核心
      - /mnt/unas/data/docker/dockege:/app/data
      # 配置文件目录
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
      # compose的存放路径
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 5001:5001
      # WebUI http端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3