# 官方文档
# https://xdocs.hanxi.cc
# https://xdocs.hanxi.cc/issues
# https://github.com/hanxi/xiaomusic
# https://hub.docker.com/r/hanxi/xiaomusic
# https://post.smzdm.com/p/azoxq2p0
# 问题合集：https://github.com/hanxi/xiaomusic/issues/99# 自定义口令功能：https://github.com/hanxi/xiaomusic/issues/105

# 型号与产品名称对照：https://home.miot-spec.com/s/xiaomi.wifispeaker

# 本地音乐会搜索目录下上面格式的文件，下载的歌曲是 mp3 格式的。 已知 L05B L05C LX06 L16A 不支持 flac 格式。 如果格式不能播放可以打开

# 支持语音口令
# 【播放歌曲】，播放本地的歌曲
# 【播放歌曲+歌名】，比如：播放歌曲周杰伦晴天
# 【上一首】
# 【下一首】
# 【单曲循环】
# 【全部循环】
# 【随机播放】
# 【关机】，【停止播放】，两个效果是一样的。
# 【刷新列表】，当复制了歌曲进 music 目录后，可以用这个口令刷新歌单。
# 【播放列表+列表名】，比如：播放列表其他。
# 【加入收藏】，把当前播放的歌曲加入收藏歌单。
# 【取消收藏】，把当前播放的歌曲从收藏歌单里移除。
# 【播放列表收藏】，这个用于播放收藏歌单。
# 【播放本地歌曲+歌名】，这个口令和播放歌曲的区别是本地找不到也不会去下载。
# 【播放列表第几个+列表名】，具体见：https://github.com/hanxi/xiaomusic/issues/158
# 【搜索播放+关键词】，会搜索关键词作为临时搜索列表播放，比如说【搜索播放林俊杰】，会播放所有林俊杰的歌。
# 【本地搜索播放+关键词】，跟搜索播放的区别是本地找不到也不会去下载。
# 隐藏玩法: 对小爱同学说播放歌曲小猪佩奇的故事，会先下载小猪佩奇的故事，然后再播放小猪佩奇的故事。

---
version: "3"
# 最后编辑时间：2025-03-13
services:
  xiaomusic:
    image: hanxi/xiaomusic:latest
    # 镜像地址
    container_name: xiaomusic
    # 容器名字
    hostname: xiaomusic
    # 主机名
    volumes:
      - /mnt/unas/data/docker/xiaomusic:/app/conf
      # 配置文件目录
      - 【这里替换为你的音乐库目录】:/app/music
      # 音乐库，如有多个目录可以按照以下格式增添多个
      # - 【这里替换为你的音乐库目录】:/app/music/目录a
      # - 【这里替换为你的音乐库目录】:/app/music/目录b
    environment:
      - XIAOMUSIC_PUBLIC_PORT=8090
      # 自定义容器WebUI端口，默认8090
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 8090:8090
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
