# 官方文档
# https://github.com/filebrowser/filebrowser
# https://hub.docker.com/r/filebrowser/filebrowser
# 部署教程
# https://github.com/filebrowser/filebrowser/blob/master/docs/installation.md
# https://post.smzdm.com/p/apvp2p2w

# 默认账号为 admin，密码看日志，存放在数据库当中

---
version: "3"
# 最后编辑时间：2025-10-29
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    # 镜像地址
    container_name: filebrowser
    # 容器名字
    hostname: filebrowser
    # 主机名
    user: root
    # 赋予root权限
    volumes:
      - /mnt/user/appdata/filebrowser/config:/config
      # 配置目录
      - /mnt/user/appdata/filebrowser/database:/database
      # 数据库目录
      - /mnt/user:/srv
      # 映射本地其他路径使其可以访问，可以自定义多个，必须在/srv之下
    environment:
      - TZ=Asia/Shanghai
      # 时区
    network_mode: bridge
    # 80端口被占用，不能用host
    # 你可以选择在 /config/settings.json 中的80端口号为自定义容器端口，再使用host网络模式
    ports:
      - 3670:80/tcp
      # WebUI http端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:80]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/filebrowser.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
