# 官网
# https://www.photopea.com

# 编译教程
# https://post.smzdm.com/p/aovl8lo7
# https://zhuanlan.zhihu.com/p/684972393

# 网友编译现成dockre镜像，支持x86和arm64v8
# https://hub.docker.com/r/mysll/ps-offline
# https://github.com/mysll/ps-offline

---
version: "3"
# 最后编辑时间：2024-05-06
services:
  photopea:
    image: mysll/ps-offline:latest
    # 镜像地址
    container_name: photopea
    # 容器名字
    hostname: photopea
    # 主机名
    entrypoint: python3 -m http.server --directory www.photopea.com 8887
    # 8887为编译的端口号，可自定义
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 8887:8887
      # WebUI http端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:8887]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/photopea_A.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
