# 官方文档
# https://hub.docker.com/r/iib0011/omni-tools

---
version: "3"
# 最后编辑时间：2025-10-25
services:
  omni-tools:
    image: iib0011/omni-tools:latest
    # 镜像地址
    container_name: omni-tools
    # 容器名字
    hostname: omni-tools
    # 主机名
    network_mode: bridge
    # 80端口被占用了，不能使用host
    ports:
      - 3177:80/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/omni-tools_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:80]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/omni-tools.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
