# 官方文档
# https://static-web-server.net
# https://github.com/static-web-server/static-web-server
# https://hub.docker.com/joseluisq/static-web-server

---
version: "3"
# 最后编辑时间：2024-10-18
services:
  static-web-server:
    image: joseluisq/static-web-server:2-alpine
    # 镜像地址
    container_name: static-web-server
    # 容器名字
    hostname: static-web-server
    # 主机名
    volumes:
      - ./static-web-server:/public
      # 静态页面存储路径
    environment:
      - SERVER_ROOT=/public
      # 自定义容器的静态页面存储路径，一般不用动，保持默认
    network_mode: bridge
    # 80端口被占用，不能用host
    ports:
      - 5680:80/tcp
      # WebUI http端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3