# 官方文档
# https://www.mtab.cc
# https://github.com/tsxcw/mtab
# https://hub.docker.com/itushan/mtab
# 演示入口，账号：admin；密码：123456
# https://demo.mtab.cc
# 视频教程
# https://www.bilibili.com/video/BV1ee411B7fY

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  mtab:
    image: itushan/mtab:latest
    # 镜像地址
    container_name: mtab
    # 容器名字
    hostname: mtab
    # 主机名
    volumes:
      - ./mtab:/app
      # 数据目录
    network_mode: bridge
    # 80端口被占用，不能用host
    ports:
      - 9200:80
      # WebUI 端口
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
