# 官方文档
# https://github.com/AdguardTeam/AdGuardHome
# https://hub.docker.com/r/adguard/adguardhome

# 部署使用教程
# https://divineengine.net/article/installing-adguard-home-on-synology-dsm-with-docker
# https://post.smzdm.com/p/arq2zvvg
# https://www.orcy.net.cn/1088.html
# https://www.voidking.com/dev-docker-adguardhome
# https://atpx.com/blog/adguard-home-doh-server-with-docker

# 注意：初始化时设置的是容器端口，WebUI端口初始化设置默认是80，记得修改成3000

---
version: "3"
# 最后编辑时间：2024-11-18
services:
  adguard:
    image: adguard/adguardhome:latest
    # 镜像地址
    container_name: adguard
    # 容器名字
    hostname: adguard
    # 主机名
    volumes:
      - /volume1/docker/adguard:/opt/adguardhome/work
      - /volume1/docker/adguard:/opt/adguardhome/conf
      # 配置文件目录
    environment:
      - TZ=Asia/Shanghai
      # 时区
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 53:53
      # - 53:53/udp
      # DNS服务，拦截协议端口，必须
      # - 3000:3000
      # WebUI 端口，必须
      ########################################
      # - 80:80
      # - 443:443
      # 如果您打算将 AdGuard Home 的身份运行 一个 HTTPS/DNS-over-HTTPS 服务器，请启用
      # - 67:67/udp
      # - 68:68
      # - 68:68/udp
      # 如果您打算将 AdGuard Home 用作 DHCP 服务器，请启用
      # - 853:853
      # 如果您打算将 AdGuard Home 作为 DNS-over-TLS 服务器运行，请启用
      # - 853:853/udp
      # 如果您打算将 AdGuard Home 作为 DNS-over-QUIC 服务器运行，请启用
      # - 5443:5443
      # - 5443:5443/udp
      # 如果您要运行 AdGuard ，请添加 Home 作为 DNSCrypt 服务器，请启用
      # - 6060:6060
      # 调试配置文件
      ########################################
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:3000]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/adguard.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
