# 官方文档
# https://github.com/amtoaer/bili-sync
# https://hub.docker.com/r/amtoaer/bili-sync-rs
# 部署教程
# https://blog.hesuisui.top/archives/Docker-Bili-Sync

---
version: "3"
# 最后编辑时间：2024-04-23
services:
  bili-sync-rs:
    image: amtoaer/bili-sync-rs:latest
    # 镜像地址
    container_name: bili-sync-rs
    # 容器名字
    hostname: bili-sync-rs
    # 主机名
    volumes:
    - 【这里替换为你的docker数据存放目录】/bili-sync-rs:/app/.config/bili-sync
    # 配置目录
    - 【这里替换为你的数据存放目录】/B站收藏同步:/downloads
    # 默认下载目录
    environment:
    - TZ=Asia/Shanghai
    # 时区
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      # 该镜像只在后台运行，无WebUI 
      icon: http://IP:PORT/i/user_01/bili-sync.png
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: /mnt/user/LOGO/bili-sync.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑