# 官方文档
# https://blog.akimio.top/posts/1031
# https://github.com/Akimio521/AutoFilm
# https://hub.docker.com/r/akimio/autofilm

# 需要搭配alist使用，需要提前配置好 /config/config.yaml 才可使用
# https://github.com/Akimio521/AutoFilm/blob/main/config/config.yaml.example
# 本项目已经集成在moviepilot中，如需单独使用，则部署吧，Just do it!

---
version: "3"
# 最后编辑时间：2024-11-18
services:
  autofilm:
    image: akimio/autofilm:latest
    # 镜像地址
    container_name: autofilm
    # 容器名字
    hostname: autofilm
    # 主机名
    volumes:
      - 【这里替换为你的docker数据存放目录】/autofilm/config:/config
      # 配置文件目录，记得先配置好config.yaml文件再启动
      - 【这里替换为你的docker数据存放目录】/autofilm/logs:/logs
      # 日志目录
      - 【这里替换为你的数据存放目录】/autofilm-strm:/strm
      # 媒体库目录，可以自定义多个，对映射不熟练的建议两边都写相同的nas本机的绝对路径
      # 记得把该路径映射到EMBY和JF上，不然无法使其添加入库
      # - 【这里替换为你的数据存放目录】:/【这里替换为你的数据存放目录的名字】
      
    network_mode: host
    # 不存在webui，这一条网络模式仅用于不然它创建一个私有网段，强迫症而已
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: /mnt/user/LOGO/autofilm.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
