# 官方文档
# https://hub.docker.com/r/whyour/qinglong

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  qinglong:
    image: whyour/qinglong:latest
    # 镜像地址
    container_name: qinglong
    # 容器名字
    hostname: qinglong
    # 主机名
    # network_mode: bridge
    volumes:
      - 【这里替换为你的docker数据存放目录】/qinglong:/ql/data
    environment:
      - QlPort=5700
      # 自定义WebUI端口号，默认为5700
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 5700:5700
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:5699]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/qinglong_B.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑