# 官方文档
# https://hub.docker.com/r/synctvorg/synctv
# 默认账号/密码：root/root

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  synctv:
    image: synctvorg/synctv:latest
    # 镜像地址
    container_name: synctv
    # 容器名字
    hostname: synctv
    # 主机名
    volumes:
      - 【这里替换为你的docker数据存放目录】/synctv:/root/.synctv
      # 配置文件目录
    network_mode: bridge
    # 推荐使用bridge模式，8080有别的docker镜像要用
    ports:
      - 20202:8080
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:8080]
      net.unraid.docker.icon: /mnt/user/LOGO/synctv.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
