# 官方文档
# https://alist.nn.ci/zh/guide
# https://hub.docker.com/r/xhofe/alist
# 正式版tag为latest-aio，测试版为beta-aio
# aio为带全部功能，推荐

## 3.25.0以上版本将密码改成加密方式存储的hash值，无法直接反算出密码，如果忘记了密码只能通过重新 随机生成 或者 手动设置
# 随机生成一个密码，`admin`为账号名，注意替换
# docker exec -it alist ./alist admin random
# 手动设置一个密码，`admin`为账号名，`NEW_PASSWORD`是指你需要设置的密码，注意替换
# docker exec -it alist ./alist admin set NEW_PASSWORD

---
version: "3"
# 最后编辑时间：2025-05-28
services:
  alist:
    image: xhofe/alist-aria2:latest-aio
    # 镜像地址
    container_name: alist
    # 容器名字
    hostname: alist
    # 主机名
    # privileged: true
    # 特权模式，赋予容器几乎与主机相同的权限
    volumes:
      - /mnt/emmc/docker/alist:/opt/alist/data
      # 配置目录
      - /mnt:/mnt
      - /home:/home
      # 数据目录
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      # 时区
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 5244:5244/tcp
      # WebUI http端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
