# 官方文档
# https://github.com/XGHeaven/homebox
# https://hub.docker.com/r/xgheaven/homebox

# 教程
# https://blog.zeruns.tech/archives/598.html
# https://www.bilibili.com/opus/759899273897705489
# https://blog.mingqin.wang/docker搭建一款专为家庭网络打造的网络工具箱

# 本软件需要一个服务端进行部署，然后通过客户端访问网页进行测试
# 当需要对万兆以上网络测试的时候，需要保证客户端的性能(主要为 CPU 单核)足够强劲，否则可能会成为瓶颈。 具体的要求可以看后文的性能测试(https://github.com/XGHeaven/homebox?tab=readme-ov-file#Performance)

---
services:
# 最后编辑时间：2024-12-09
  homebox:
    image: xgheaven/homebox:latest
    # 镜像地址
    container_name: homebox
    # 容器名字
    hostname: homebox
    # 主机名
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # 推荐直接host网络模式
    # ports:
      # - 3300:3300
      # WebUI端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:3300]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/homebox.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
