# 官方文档
# https://cryptgeon.com
# https://github.com/cupcakearmy/cryptgeon
# https://hub.docker.com/r/cupcakearmy/cryptgeon
# https://blog.laoda.de/archives/docker-compose-install-cryptgeon

---
version: '3.8'
# 最后编辑时间：2024-11-22
services:
  redis:
    image: redis:latest
    # 镜像地址
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    # 设置大小限制，详可见 https://redis.io/docs/manual/eviction
    restart: unless-stopped

  cryptgeon:
    image: cupcakearmy/cryptgeon:latest
    # 镜像地址
    container_name: cryptgeon
    # 容器名字
    hostname: cryptgeon
    # 主机名
    depends_on:
      - redis
      # 关联redis
    environment:
      # - REDIS=redis://redis/
      # 要连接到的 Redis URL，具体见 https://docs.rs/redis/latest/redis/#connection-parameters
      # 格式：redis://[<username>][:<password>@]<hostname>[:port][/[<db>][?protocol=<protocol>]]
      # 非特殊需要，一般不写
      - SIZE_LIMIT=4 MiB
      # 最大限制为 512 MiB，默认为 4 MiB
      - ALLOW_ADVANCED=false
      # 允许自定义配置，默认为false
      - ALLOW_FILES=false
      # 允许上传文件，默认为false
      - MAX_VIEWS=100
      # 最大视图数，默认为100
      - MAX_EXPIRATION=360
      # 最大过期时间(分钟)，默认为360
    ports:
      - 8270:8000
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:8000]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/cryptgeon.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
