# 官方文档，强烈建议耐心看完
# https://github.com/jxxghp/moviepilot
# https://hub.docker.com/r/jxxghp/moviepilot
# https://wiki.movie-pilot.org

# 插件库
# https://github.com/jxxghp/MoviePilot-Plugins
# https://github.com/thsrite/MoviePilot-Plugins
# https://github.com/honue/MoviePilot-Plugins
# https://github.com/InfinityPacer/MoviePilot-Plugins

# 大部分配置可启动后通过WEB管理界面进行配置，但仍有部分配置需要通过环境变量/配置文件进行配置。
# MP v2.0.7及以上版本，已支持通过UI进行用户认证：点击用户头像 -> 用户认证，无需配置环境变量，模板继续保留原有的认证变量
# 配置文件映射路径：/config，配置项生效优先级：环境变量 > env文件（或通过WEB界面配置） > 默认值。
# 该模板将部分参数都简化掉，留下一些个人认为必要的参数以便于修改，剩下的参数设置可以在MP内设置

####################
# 重要内容，硬链接只能够存在于同一个存储池上
# 重要内容，硬链接只能够存在于同一个存储池上
# 重要内容，硬链接只能够存在于同一个存储池上
#
# /存储池/.../media
#             |---/下载
#             |
#             |---/电影
#             |     |---/国产电影
#             |     |---/欧美电影
#             |     |---/日韩电影
#             |
#             |---/电视剧
#                    |---/国产电视剧
#                    |---/欧美电视剧
#                    |---/日韩电视剧
#
# ①：/存储池1/meida——————media为共享文件夹，存储池预设为第1个存储池，请根据自己实际情况修改【这是实际路径】
# ②：/存储池1/meida/下载——————用于QB和TR下载，MP中设置对应的容器路径/downloads用于传递【这是实际路径】
# ③：/存储池1/meida/电影；/存储池1/meida/电视剧——————用于媒体库的分类存放，可根据自己需要增添【这是实际路径】
# ④：请在MP设置中，把下载目录设置为“/meida/下载”；把 电影/电视剧 等分类的目录设置从“/meida”开始选择【这是容器路径】
# ⑤：MP和QB,TR都使用同一条路径映射“/meida/下载”【必须完全一样】
# 不懂可以看看MP-01和MP-03这两张图，MP-02是效果图，实在不是，你不如直接用自动化媒体库一条龙部署那张模板参考参考怎么部署的

---
version: "3"
# 最后编辑时间：2025-01-26
# 更新日志：不定期翻新配置文件，增加认证站点：sunny,ptcafe,ptzone,kufei,yemapt
# V2和V1的配置单几乎是一毛一样的，但是互不兼容，可以共存，本模板采用的还是和V1一样的配置单，只有自定义容器端口由33033改成了55055
services:
  moviepilot-v2:
    image: jxxghp/moviepilot-v2:latest
    # 镜像地址
    container_name: moviepilot-v2
    # 容器名字
    hostname: moviepilot-v2
    # 主机名
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    # privileged: true
    # 特权模式，赋予容器几乎与主机相同的权限
    network_mode: host
    # 推荐自定义MP的WebUI端口，然后直接用host模式，webui为"nas的ip:55055"
      
########################################
## 第一次运行时，moviepilot 会下载大量文件到本地，请在留意日志中的进度，如果有什么问题，可以寻找网友求助
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # 使MP支持内建的重启操作，用于自动更新后重启
      - /share/Container/moviepilot-v2/core:/moviepilot
      # 程序主目录
      - /share/Container/moviepilot-v2/config:/config
      # 配置目录
      - /share:/media
      # 设置一个总目录，以便于后续目录配置的统一修改，也可以自定义，但一定要确认参数无误，见上目录结构说明的④⑤
      
########################################
    environment:
      - MOVIEPILOT_AUTO_UPDATE=true
      # 设置容器重启时自动更新，true/release/dev/false，默认release，插件的自动更新要设置为true
      # 需要能正常连接Github 注意：如果出现网络问题可以配置PROXY_HOST
      - API_TOKEN=1234567890123456
      # API密钥，V1版本默认为moviepilot，V2版本需要手动配置为大于等于16个字符的复杂字符串
      # 如配置不符合要求将会强制重新生成，可在首次启动的启动日志或env配置文件中查看最新的值
      # 在媒体服务器Webhook、微信回调等地址配置中需要加上 ?token= 该值
      
      - NGINX_PORT=55055
      # WebUI服务端口，默认为3000，预设为55055，可自行修改，不能和API服务端口3001冲突
      - SUPERUSER=admin
      # 超级管理者用户名，默认为admin，可在MP内修改，初次安装后失效
      # 密码在日志里，只会在第一次部署出现，否则得删除/config/user.db这个文件重新配置，注意查看，初次安装后失效，可在MP内修改

      # - PROXY_HOST=【IP:PORT】
      # 网络代理，访问themoviedb或者重启更新需要使用代理访问，如果你没有配置魔法就注释掉
      # 格式为http(s)://ip:port、socks5://user:pass@host:port
      - BIG_MEMORY_MODE=false
      # 是否使用大内存模式，true/false，默认不使用，开启后会增加缓存数量，占用更多的内存，但响应速度会更快
      - UMASK=022
      # 默认创建新文件的权限，一般写022，MP默认为000，可以不写，也可以考虑设置为022
      
########################################
#### 认证站点 ####
      - AUTH_SITE=iyuu,agsvpt,audiences,discfan,freefarm,haidan,hddolby,hdfans,hhclub,icc2022,ptba,ptvicomo,wintersakura,xingtan,zmpt,sunny,ptcafe,ptzone,kufei,yemapt
      ## 只有通过后才能使用站点相关功能，支持配置多个认证站点，使用英文逗号，进行分隔，会依次执行认证操作，直到有一个站点认证成功
      ## UID为网站分配给你的数字ID，请在个人信息内查看，切勿泄露
      ## 密钥在控制面板中查看，切勿泄露
      ## 以下认证只需要写一个即可，记得把#注释去掉
      ## 推荐红豆饭，因为支持iyuu和mp的认证（2024年5月注释）
########################################
      # - IYUU_SIGN=
      # iyuu的认证，输入IYUU的登录令牌即可，IYUU本身也是需要认证的
########################################
      # - HHCLUB_USERNAME=
      # - HHCLUB_PASSKEY=
      # hhclub的用户名和密钥，注意这里是用户名
########################################
      # - AUDIENCES_UID=
      # - AUDIENCES_PASSKEY=
      # audiences的用户UID和密钥
########################################
      # - HDDOLBY_UID=
      # - HDDOLBY_PASSKEY=
      # hddolby的用户UID和密钥
########################################
      # - ZMPT_UID=
      # - ZMPT_PASSKEY=
      # zmpt的用户UID和密钥
########################################
      # - FREEFARM_UID=
      # - FREEFARM_PASSKEY=
      # freefarm的用户UID和密钥
########################################
      # - HDFANS_UID=
      # - HDFANS_PASSKEY=
      # hdfans的用户UID和密钥
########################################
      # - WINTERSAKURA_UID=
      # - WINTERSAKURA_PASSKEY=
      # wintersakura的用户UID和密钥
########################################
      # - LEAVES_UID=
      # - LEAVES_PASSKEY=
      # leaves的用户UID和密钥
########################################
      # - PTBA_UID=
      # - PTBA_PASSKEY=
      # ptba的用户UID和密钥
########################################
      # - ICC2022_UID=
      # - ICC2022_PASSKEY=
      # icc2022的用户UID和密钥
########################################
      # - XINGTAN_UID=
      # - XINGTAN_PASSKEY=
      # xingtan的用户UID和密钥
########################################
      # - PTVICOMO_UID=
      # - PTVICOMO_PASSKEY=
      # ptvicomo的用户UID和密钥
########################################
      # - AGSVPT_UID=
      # - AGSVPT_PASSKEY
      # agsvpt用户UID和密钥
########################################
      # - HDKYL_UID=
      # - HDKYL_PASSKEY=
      # hdkyl的用户UID和密钥
########################################
      # - QINGWA_UID=
      # - QINGWA_PASSKEY=
      # qingwa的用户UID和密钥
########################################
      # - DISCFAN_UID=
      # - DISCFAN_PASSKEY=
      # discfan的用户UID和密钥
########################################
      # - HAIDAN_UID=
      # - HAIDAN_PASSKEY=
      # haidan的用户UID和密钥
########################################
      # - ROUSI_UID=
      # - ROUSI_PASSKEY=
      # rousi的用户UID和密钥
########################################
      # - SUNNY_UID=
      # - SUNNY_PASSKEY=
      # sunny的用户UID和密钥
########################################
      # - PTCAFE_UID=
      # - PTCAFE_PASSKEY=
      # ptcafe的用户UID和密钥
########################################
      # - PTZONE_UID=
      # - PTZONE_PASSKEY=
      # ptzone的用户UID和密钥
########################################
      # - KUFEI_UID=
      # - KUFEI_PASSKEY=
      # kufei的用户UID和密钥
########################################
      # - YEMAPT_UID=
      # - YEMAPT_PASSKEY=
      # yemapt的用户UID和密钥
########################################
