# 根据PT站站规，MP作者文档，ANI-RSS作者声明，严禁在互联网任何公开场合讨论相关内容，本模板同上
# 根据PT站站规，MP作者文档，ANI-RSS作者声明，严禁在互联网任何公开场合讨论相关内容，本模板同上
# 根据PT站站规，MP作者文档，ANI-RSS作者声明，严禁在互联网任何公开场合讨论相关内容，本模板同上
# 根据PT站站规，MP作者文档，ANI-RSS作者声明，严禁在互联网任何公开场合讨论相关内容，本模板同上
# 根据PT站站规，MP作者文档，ANI-RSS作者声明，严禁在互联网任何公开场合讨论相关内容，本模板同上
# 根据PT站站规，MP作者文档，ANI-RSS作者声明，严禁在互联网任何公开场合讨论相关内容，本模板同上
# 根据PT站站规，MP作者文档，ANI-RSS作者声明，严禁在互联网任何公开场合讨论相关内容，本模板同上
# 根据PT站站规，MP作者文档，ANI-RSS作者声明，严禁在互联网任何公开场合讨论相关内容，本模板同上
# 根据PT站站规，MP作者文档，ANI-RSS作者声明，严禁在互联网任何公开场合讨论相关内容，本模板同上

# 官方文档，强烈建议耐心看完
# https://github.com/jxxghp/moviepilot
# https://hub.docker.com/r/jxxghp/moviepilot
# https://wiki.movie-pilot.org

# 插件库
# https://github.com/jxxghp/MoviePilot-Plugins
# https://github.com/thsrite/MoviePilot-Plugins
# https://github.com/honue/MoviePilot-Plugins
# https://github.com/InfinityPacer/MoviePilot-Plugins

# 大部分配置可启动后通过WEB管理界面进行配置，但仍有部分配置需要通过环境变量/配置文件进行配置。
# MP v2.0.7及以上版本，已支持通过UI进行用户认证：点击用户头像 -> 用户认证，无需配置环境变量，模板继续保留原有的认证变量
# 配置文件映射路径：/config，配置项生效优先级：环境变量 > env文件（或通过WEB界面配置） > 默认值。
# 该模板将部分参数都简化掉，留下一些个人认为必要的参数以便于修改，剩下的参数设置可以在MP内设置

####################
# 重要内容，硬链接只能够存在于同一个存储池上
# 重要内容，硬链接只能够存在于同一个存储池上
# 重要内容，硬链接只能够存在于同一个存储池上
#
# /Volume1/media
#           |---/动漫
#           |---/下载
#           |
#           |---/电影
#           |     |---/国产电影
#           |     |---/欧美电影
#           |     |---/日韩电影
#           |
#           |---/电视剧
#                  |---/国产电视剧
#                  |---/欧美电视剧
#                  |---/日韩电视剧

# ①：/Volume1/media——————media为共享文件夹，存储池预设为第1个存储池，请根据自己实际情况修改【这是实际路径】
# ②：/Volume1/media/下载——————用于QB和TR下载，MP中设置对应的容器路径/downloads用于传递【这是实际路径】
# ③：/Volume1/media/电影；/Volume1/media/电视剧——————用于媒体库的分类存放，可根据自己需要增添【这是实际路径】
# ④：请在MP设置中，把下载目录设置为“/meida/下载”；把 电影/电视剧 等分类的目录设置从“/meida”开始选择【这是容器路径】
# ⑤：MP和QB,TR都使用同一条路径映射“/meida/下载”【必须完全一样】
# 不懂可以看看MP-01和MP-03这两张图，MP-02是效果图，实在不是，你不如直接用自动化媒体库一条龙部署那张模板参考参考怎么部署的

---
version: "3"
# 最后编辑时间：2025-02-27
# 更新日志：不定期翻新配置文件，增加认证站点：sunny,ptcafe,ptzone,kufei,yemapt
# V2和V1的配置单几乎是一毛一样的，但是互不兼容，可以共存，本模板采用的还是和V1一样的配置单，只有自定义容器端口由33033改成了55055
services:
  moviepilot-v2:
    image: jxxghp/moviepilot-v2:latest
    # 镜像地址
    container_name: moviepilot-v2
    # 容器名字
    hostname: moviepilot-v2
    # 主机名
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    network_mode: host
    # 推荐自定义MP的WebUI端口，然后直接用host模式，webui为"nas的ip:55055"
      
########################################
## 第一次运行时，moviepilot 会下载大量文件到本地，请在留意日志中的进度，如果有什么问题，可以寻找网友求助
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # 使MP支持内建的重启操作，用于自动更新后重启
      - /Volume1/docker/moviepilot-v2/core:/moviepilot/.cache/ms-playwright
      # 程序主目录
      - /Volume1/docker/moviepilot-v2/config:/config
      # 配置目录
      - /Volume1:/media
      # 设置一个总目录，以便于后续目录配置的统一修改，也可以自定义，但一定要确认参数无误，见上目录结构说明的④⑤

      # - /Volume1/docker/qbittorrent/qBittorrent/BT_backup:/QB-BT
      # - /Volume1/docker/docker/transmission/torrents:/TR-BT
      # 用于自动转种所使用的路径，分别为QB配置目录里面的BT_backup路径地址，TR配置目录里面的torrents路径地址，请根据实际情况修改，模板仅供参考

########################################
    environment:
      - API_TOKEN=1234567890123456
      # API密钥，V1版本默认为moviepilot，V2版本需要手动配置为大于等于16个字符的复杂字符串
      # 如配置不符合要求将会强制重新生成，可在首次启动的启动日志或env配置文件中查看最新的值
      # 在媒体服务器Webhook、微信回调等地址配置中需要加上 ?token= 该值
      
      - NGINX_PORT=55055
      # WebUI服务端口，默认为3000，预设为55055，可自行修改
      - PORT=55056
      # API端口，默认为3001，预设为55056，可自行修改

      - SUPERUSER=admin
      - SUPERUSER_PASSWORD=password
      # 超级管理者用户名和密码，默认为admin/password，可在MP内修改，初次安装后失效
      # 密码如果忘记，可以文本形式打开 /config/logs/moviepilot.log 该文件，查看日志获取，否则得删除pgsql的所有文件，然后重新配置，注意查看，可在MP内修改

      - UMASK=022
      # 默认创建新文件的权限，一般写022，MP默认为000，可以不写，也可以考虑设置为022
