# 官方文档
# https://github.com/snowdreamtech/frp
# https://github.com/fatedier/frp
# https://github.com/stilleshan/frps
# 镜像地址
# https://hub.docker.com/r/qq918652593/easy-frpc
# 软件作者：隔壁小王

# 相关教程
# https://gofrp.org/zh-cn/docs
# https://freefrp.net/docs

# 进入ui后点击初始化有提供默认配置，有详细的中文注释，可以直接在ui上操作配置和服务，快去体验吧！！

---
version: "3"
# 最后编辑时间：2026-06-20
services:
  easy-frpc:
    image: qq918652593/easy-frpc:latest
    # 镜像地址，仅支持amd64
    container_name: easy-frpc
    # 容器名字
    volumes:
      - 【这里替换为你的docker数据存放目录】/frp/easy-frpc:/app/data
      # 配置文件目录
    environment:
      - TZ=Asia/Shanghai
      # 时区
    network_mode: bridge
    # network_mode: host
    # 推荐直接使用bridge网络模式，frpc只需要写好配置文件就可以生效，除非5000端口没有占用，模板预设使用bridge
    # easy-frpc的可视化在线配置面板端口默认为5000，具体看 frps.toml 中的设置
    ports:
      - 50001:5000
      # easy-frpc的可视化在线配置面板
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:5000]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/frps.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
