# 官方文档
# https://easysend.channer.cn
# https://github.com/bitporo/easy-send
# https://gitee.com/bitporo/easy-send
# https://easysend.channer.cn/project-docker.html

# 一款不需要在接收端安装就可在局域网环境内共享文本及文件的小软件，仅需一台主机电脑启动，需要获取共享的电脑或手机无需安装只需使用浏览器访问即可
# 支持windows、linux、mac，支持国产操作系统多平台
# 支持node环境及docker运行，可访问官网下载部署
# 采用electron-egg + uniapp + primevue ui实现
# 支持一键复制共享地址、支持手机二维码扫描、支持拖拽文件上传、支持图片预览

---
version: "3"
# 最后编辑时间：2024-11-03
services:
  easysend:
    image: easysend:v1.3.0
    # 镜像地址，仅支持amd64，该镜像无法拉取，并没有发布在dockerhub上，需要到作者123盘上下载，然后导入
    container_name: easysend
    # 容器名字
    hostname: easysend
    # 主机名
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 7072:7072
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/easy-send.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:7072]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/easy-send.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
