# 官方文档
# https://github.com/wu529778790/panhub.shenzjd.com
# https://hub.docker.com/r/wu529778790/panhub.shenzjd.com
# 部署教程：https://www.iyanxi.com/p/3ac006f208d5

---
version: "3"
# 最后编辑时间：2026-01-07
services:
  panhub:
    image: wu529778790/panhub.shenzjd.com:latest
    # 镜像地址
    container_name: panhub
    # 容器名字
    hostname: panhub
    # 主机名
    # volumes:
      # - 【这里替换为你的docker数据存放目录】/panhub:/app/data
      # 数据库持久化，默认不使用，但推荐
    environment:
      - PORT=3755
      # 自定义容器 WebUI 端口
    network_mode: host
    # 推荐自定义容器WebUI端口+ host网络模式
    ports:
      - 3755:3755
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:3755]
      net.unraid.docker.icon: /mnt/user/LOGO/panhub.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
