# 官方文档
# https://wallabag.org
# https://doc.wallabag.org/en/admin/installation/requirements.html
# https://github.com/wallabag/wallabag
# https://hub.docker.com/r/wallabag/wallabag

# sqlite部署教程
# https://www.amjun.com/2329.html
# https://blog.chenjia.info/posts/2024/08/docker-compose快速搭建文章保存服务wallabag

# pgsql部署教程
# https://tech.yemengstar.com/docker-wallabag-let-me-read-it-later
# https://blog.laoda.de/archives/docker-compose-install-wallabag
# https://www.youtube.com/watch?v=KURD8cY9fs0

# 部署的搭配方式有三种，是用自带的sqlite，pgsql，pgsql，还可以搭配上redis
# 但是部署后都出现500错误，不晓得如何解决，只有不使用外部数据库的正常启动
# 并且使用群晖/绿联自带的compose部署均无法正常启动，omv/dpanel进行compose部署都正常，其余nas还没测试，因而暂时不写
# 默认账号密码：wallabag / wallabag

---
version: "3"
# 最后编辑时间：2025-01-02
services:
  wallabag:
    image: wallabag/wallabag:latest
    # 镜像地址
    container_name: wallabag
    # 容器名字
    hostname: wallabag
    # 主机名
    volumes:
      - 【这里替换为你的docker数据存放目录】/wallabag/data:/var/www/wallabag/data
      # 数据缓存目录
      - 【这里替换为你的docker数据存放目录】/wallabag/images:/var/www/wallabag/web/assets/images
      # 图片缓存目录
    environment:
      - TZ=Asia/Shanghai
      # 时区
      - SYMFONY__ENV__DOMAIN_NAME=http://192.168.1.88:4652
      # 模板写的是局域网WebUI地址，建议写反代的域名地址
      - SYMFONY__ENV__LOCALE=zh
      # 设置默认语言为中文
    network_mode: bridge
    # 80端口被占用，不能用host
    ports:
      - 4652:80
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:80]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/wallabag.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
