# 官方文档
# http://hub.docker.com/libretranslate/libretranslate
# https://github.com/LibreTranslate/LibreTranslate
# https://libretranslate.com

---
version: "3"
# 最后编辑时间：2024-06-14
services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    # 镜像地址
    container_name: libretranslate
    # 容器名字
    hostname: libretranslate
    # 主机名
    command: --load-only zh,en
    # 创建镜像时会拉取语言模型，每个模型的体积都很大，下载还很慢，这里可以设置只拉取特定语种翻译模型，如果需要，也可以添加de,es,fr,ru等语言包
    environment:
      - LT_PORT=5100
      # 自定义容器WebUI端口，默认为5000，由于群晖也用了5000，所以这里修改掉
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 5100:5100
      # WebUI 端口
    restart: always
    # 重启策略
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:5100]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/libretranslate.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
