# 官方文档
# https://hub.docker.com/r/byaidu/pdf2zh
# https://github.com/Byaidu/PDFMathTranslate

# 演示站
# https://pdf2zh.com
# https://huggingface.co/spaces/reycn/PDFMathTranslate-Docker
# https://www.modelscope.cn/studios/AI-ModelScope/PDFMathTranslate

---
version: "3"
# 最后编辑时间：2025-02-26
services:
  pdf2zh:
    image: byaidu/pdf2zh:latest
    # 镜像地址
    container_name: pdf2zh
    # 容器名字
    hostname: pdf2zh
    # 主机名
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 7860:7860
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:7860]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/pdf2zh.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
