# 官方文档
# https://serverbee.app
# https://serverbee.app/zh/starter/getting-started
# https://hub.docker.com/r/zingerbee/serverbee-web

# 控制端：ServerBee APP (目前仅有iOS客户端)
# 服务端（被控端）：server_bee-backend 或 ServerMilk
# 密钥需要在客户端中生成

# 部署教程
# https://tyooe.com/serverbee
# https://post.smzdm.com/p/azovo6z0
# https://zhuanlan.zhihu.com/p/10125273070

---
version: "3"
# 最后编辑时间：2024-12-25
services:
  serverbee-web:
    image: zingerbee/serverbee-web:latest
    # 镜像地址
    container_name: serverbee-web
    # 容器名字
    hostname: serverbee-web
    # 主机名，此处修改为设备名称
    privileged: true
    # 特权模式，赋予容器几乎与主机相同的权限
    command: -p 9527
    # 自定义容器端口
    volumes:
      - /proc:/proc
      - /dev:/dev
      - /sys:/sys
      - /etc:/etc
      - /run/media:/run/media
      - /sys/class/net:/sys/class/net
      # 照抄
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # 推荐自定义容器端口，使用host网络模式
    # ports:
      # - 9527:9527
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:9527]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/serverbee.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
