# 官方文档
# https://hub.docker.com/r/linuxserver/mariadb
# https://mariadb.com

---
version: "3"
# 最后编辑时间：2024-03-11
services:
  mariadb:
    image: linuxserver/mariadb:latest
    # 镜像地址
    container_name: mariadb
    # 容器名字
    hostname: mariadb
    # 主机名
    volumes:
      - /share/Container/mariadb:/config
      # 配置文件目录
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      # mariadb管理者密码，账户为root，预设为mariadb
      # 不推荐其他容器都直接使用root管理者账号使用数据库，而是在数据库中创建子账号来访问子数据库
      - PUID=1000
      - PGID=100
      # 用户和用户组权限，ssh中使用“id 用户名”查看，用户组一般为100(users)
      # 第一个用户而言，群晖为1026，威联通为1000，新绿联为1001，linux类系统一般为1000，后续用户均+1
      - UMASK=022
      # 默认创建新文件的权限，一般写022
      - TZ=Asia/Shanghai
      # 时区

      # - MYSQL_DATABASE=
      # - MYSQL_USER=
      # - MYSQL_PASSWORD=
      # 在创建容器时，自动创建一个预设的子数据库，子账号及其密码，默认不使用

      # - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql
      # 远程连接别的服务器上的数据库，需要就写
    network_mode: bridge
    # 不能用host部署
    ports:
      - 3306:3306/tcp
      # 非WebUI网页界面，直接调用即可
    restart: always
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
