# 官方文档
# https://www.audiobookshelf.org/
# https://www.audiobookshelf.org/docs/#docker-compose-install
# https://hub.docker.com/r/advplyr/audiobookshelf
# https://github.com/advplyr/audiobookshelf
# https://blog.lzw.ink/archives/audiobookshelf

---
version: "3"
# 最后编辑时间：2025-04-06
services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    # 镜像地址
    container_name: audiobookshelf
    # 容器名字
    hostname: audiobookshelf
    # 主机名
    volumes:
      - /share/Container/audiobookshelf/config:/config
      # 配置文件目录
      - /share/Container/audiobookshelf/metadata:/metadata
      # 元数据目录
      - 【这里替换为你的数据存放目录】/有声读物:/audiobooks
      # 有声读物目录
      - 【这里替换为你的数据存放目录】/播客:/podcasts
      # 播客目录
    environment:
      - PORT=13378
      # 自定义容器端口，默认为80，建议自定义容器端口，然后使用host网络模式
      - TZ=Asia/Shanghai
      # 时区
    network_mode: host
    # network_mode: bridge
    # 默认的容器端口为80，建议自定义容器端口，然后使用host网络模式，因为80端口被占用了，所以使用bridge
    # ports:
      # - 13378:13378
      # WebUI http端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
