# 官方文档
# https://nextchat.dev
# https://github.com/ChatGPTNextWeb/NextChat
# https://github.com/ChatGPTNextWeb/NextChat/blob/main/README_CN.md
# https://hub.docker.com/r/yidadaa/chatgpt-next-web
# 官方演示Demo
# https://chat-gpt-next-web.vercel.app

# 教程
# https://www.huluohu.com/posts/1086
# deepseek
# https://api-docs.deepseek.com/zh-cn

---
version: "3"
# 最后编辑时间：2025-02-23
services:
  nextchat:
    image: yidadaa/chatgpt-next-web:latest
    # 镜像地址
    container_name: nextchat
    # 容器名字
    hostname: nextchat
    # 主机名
    # environment:
      # - CODE=
      # WebUI页面访问密码，预设为空
      # - PROXY_URL=http://127.0.0.1:7890
      # 代理地址，根据实际情况修改
      # - ENABLE_MCP=true
      # MCP功能，不知道是什么
    network_mode: bridge
    # 不推荐用host，除非没有被占用，有别的服务或docker需要用到3000
    ports:
      - 3880:3000
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:3000]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/nextchat.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
